package com.moviedb.tests.movies;

import static org.hamcrest.CoreMatchers.equalTo;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.samePropertyValuesAs;
import static org.testng.Assert.assertEquals;
import static org.testng.Assert.assertNotNull;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.testng.ITestResult;
import org.testng.Reporter;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.Test;

import com.moviedb.actions.MovieActions;
import com.moviedb.api.SpecBuilder;
import com.moviedb.listeners.ExtentReportManager;
import com.moviedb.pojos.movies.Movie;

import api.contants.StatusCode;
import api.utils.LogUtils;
import io.restassured.response.Response;

public class MovieCrudTests {

	@Test(description = "Ensure that new movie is created when movie details provided is valid",
			groups = {"movie_cruds", "regression", "smoke"})
	public void shouldBeAbleToCreateAMovie() {
        ExtentReportManager.log("Step 1: Creating a default movie");
        LogUtils.getLogger().info("Step 1: Creating a default movie");

		Movie moviePayload = MovieData.getMoviePayload();
		Response response = MovieActions.createMovie(moviePayload);

        ExtentReportManager.log("Step 2: Performing assertion on the API response");
        LogUtils.getLogger().info("Step 2: Performing assertion on the API response");

		Movie movieResponse = response.then()
			.spec(SpecBuilder.getResponseSpecification())
			.statusCode(StatusCode.CODE_201.getCode())
			.extract()
			.as(Movie.class);

		int movieId = movieResponse.getId();
		
        ExtentReportManager.log("Step 3: Adding movieIds to cleanUp list");
        LogUtils.getLogger().info("Step 3: Adding movieIds to cleanUp list");

		List<Integer> cleanupIds = new ArrayList<>();
		cleanupIds.add(movieId);
	    Reporter.getCurrentTestResult().setAttribute("cleanupIds", cleanupIds);

        ExtentReportManager.log("Step 4: Id of the newly created movie is: " + movieId);
        LogUtils.getLogger().info("Step 4: Id of the newly created movie is: " + movieId);

		System.out.println("Id of the newly created movie is: " + movieId);

	    assertNotNull(movieResponse.getId(), "ID should be generated by API");
	    assertEquals(movieResponse.getTitle(), moviePayload.getTitle());
	    assertThat(movieResponse, samePropertyValuesAs(moviePayload, "id"));
	}

	@Test(description = "Ensure that multiple movies are created in a single create movie request",
			groups = {"movie_cruds", "regression", "smoke"})
	public void shouldBeAbleToCreateMultipleMoviesInASingleRequest() {
        ExtentReportManager.log("Step 1: Creating movies");
        LogUtils.getLogger().info("Step 1: Creating movies");

		List<Movie> movies = new ArrayList<>();
		movies.add(MovieData.getMoviePayload());
		movies.add(MovieData.getMoviePayload());
		movies.add(MovieData.getMoviePayload());

		Response response = MovieActions.createMultipleMovies(movies);

        ExtentReportManager.log("Step 2: Performing assertion on the API response");
        LogUtils.getLogger().info("Step 2: Performing assertion on the API response");

		response.then()
			.spec(SpecBuilder.getResponseSpecification())
			.statusCode(StatusCode.CODE_201.getCode())
			.body("inserted", equalTo(movies.size()));

        ExtentReportManager.log("Step 3: Adding movieIds to cleanUp list");
        LogUtils.getLogger().info("Step 3: Adding movieIds to cleanUp list\"");

		// Extract all titles into a List using JsonPath's GPath notation
		List<String> allTitles = response.jsonPath().getList("data.title");
		assertEquals(allTitles.get(0), movies.get(0).getTitle());
		assertEquals(allTitles.get(1), movies.get(1).getTitle());
		assertEquals(allTitles.get(2), movies.get(2).getTitle());
		
		List<Integer> cleanupIds = response.jsonPath().getList("data.id");
	    Reporter.getCurrentTestResult().setAttribute("cleanupIds", cleanupIds);

		// Extracts 'data' array and maps each element to a Movie object
		List<Movie> movieList = response.jsonPath().getList("data", Movie.class);
	    assertThat(movieList.get(0), samePropertyValuesAs(movies.get(0), "id"));
	    assertThat(movieList.get(1), samePropertyValuesAs(movies.get(1), "id"));
	    assertThat(movieList.get(2), samePropertyValuesAs(movies.get(2), "id"));    
	}

	@Test(description = "Ensure that movie information is updated when valid movie id is provided",
			groups = {"movie_cruds", "regression", "smoke"})
	public void shouldBeAbleToUpdateAMovie() {
        ExtentReportManager.log("Step 1: Creating a default movie");
        LogUtils.getLogger().info("Step 1: Creating a default movie");

		Movie createMovieResponse = MovieData.createDefaultMovie();
		int movieId = createMovieResponse.getId();
	    Reporter.getCurrentTestResult().setAttribute("movieId", movieId);

        ExtentReportManager.log("Step 2: Adding movieIds to cleanUp list");
        LogUtils.getLogger().info("Step 2: Adding movieIds to cleanUp list");

		List<Integer> cleanupIds = new ArrayList<>();
		cleanupIds.add(movieId);
	    Reporter.getCurrentTestResult().setAttribute("cleanupIds", cleanupIds);
	    
        ExtentReportManager.log("Step 3: Updating budget for ID: " + movieId);
        LogUtils.getLogger().info("Step 3: Updating budget for ID: " + movieId);

		createMovieResponse.getFinance().setBudget(265000000L);
		Response response = MovieActions.updateMovie(movieId, createMovieResponse);

		ExtentReportManager.log("Step 4: Performing assertion on the API response");
        LogUtils.getLogger().info("Step 4: Performing assertion on the API response");

		Movie updateMovieResponse = response.then()
			.spec(SpecBuilder.getResponseSpecification())
			.statusCode(StatusCode.CODE_200.getCode())
			.extract()
			.as(Movie.class);

		assertEquals(updateMovieResponse.getId(), movieId);

	    assertNotNull(updateMovieResponse.getId(), "ID should be generated by API");
		assertEquals(updateMovieResponse.getTitle(), createMovieResponse.getTitle());
		assertEquals(updateMovieResponse.getFinance().getBudget(), createMovieResponse.getFinance().getBudget());
	    assertThat(updateMovieResponse, samePropertyValuesAs(createMovieResponse, "id"));
	}

	@Test(description = "Verify that a movie title can be partially updated using PATCH",
			groups = {"movie_cruds", "regression"})
	public void shouldBeAbleToPatchUpdateAMovieTitleSuccessfully() {
        ExtentReportManager.log("Step 1: Creating a default movie");
        LogUtils.getLogger().info("Step 1: Creating a default movie");

		Movie createMovieResponse = MovieData.createDefaultMovie();
		int movieId = createMovieResponse.getId();
	    Reporter.getCurrentTestResult().setAttribute("movieId", movieId);

        ExtentReportManager.log("Step 2: Adding movieIds to cleanUp list");
        LogUtils.getLogger().info("Step 2: Adding movieIds to cleanUp list");

		List<Integer> cleanupIds = new ArrayList<>();
		cleanupIds.add(movieId);
	    Reporter.getCurrentTestResult().setAttribute("cleanupIds", cleanupIds);
	    
		String newMovieTitle = "Life Is Beautiful";
		Map<String, Object> updatePayload = new HashMap<>();
		updatePayload.put("title", newMovieTitle);

		ExtentReportManager.log("Step 3: Performing assertion on the API response");
        LogUtils.getLogger().info("Step 3: Performing assertion on the API response");

	    MovieActions.patchUpdateMovie(movieId, updatePayload)
	        .then()
	            .spec(SpecBuilder.getResponseSpecification())
	            .statusCode(StatusCode.CODE_200.getCode())
	            .body("title", equalTo(newMovieTitle))
	            .body("id", equalTo(movieId));
	}

	@Test(description = "Verify that movie poster can be uploaded to a movie",
			groups = {"movie_cruds", "regression"})
	public void shouldBeAbleToUploadMoviePosterSuccessfully() {
        ExtentReportManager.log("Step 1: Creating a default movie");
        LogUtils.getLogger().info("Step 1: Creating a default movie");

		Movie createMovieResponse = MovieData.createDefaultMovie();
		int movieId = createMovieResponse.getId();

        ExtentReportManager.log("Step 2: Adding movieIds to cleanUp list");
        LogUtils.getLogger().info("Step 2: Adding movieIds to cleanUp list");

		List<Integer> cleanupIds = new ArrayList<>();
		cleanupIds.add(movieId);
	    Reporter.getCurrentTestResult().setAttribute("cleanupIds", cleanupIds);
		
		Response response = MovieActions.uploadMoviePoster("src/test/resources/data/Screenshot.png", movieId);

		ExtentReportManager.log("Step 3: Performing assertion on the API response");
        LogUtils.getLogger().info("Step 3: Performing assertion on the API response");

	    response.then()
            .spec(SpecBuilder.getResponseSpecification())
            .statusCode(StatusCode.CODE_201.getCode())
            .body("message", equalTo("Poster uploaded successfully"))
            .body("movieId", equalTo(movieId));

		System.out.println(response.jsonPath().getString("poster.filename"));
		System.out.println(response.jsonPath().getString("poster.mimetype"));
		System.out.println(response.jsonPath().getString("poster.size"));
	}

	@Test(description = "Ensure that a 200 OK is returned when a valid movie ID is deleted by an authorized user",
			groups = {"movie_cruds", "regression", "smoke"})
	public void shouldBeAbleToDeleteAMovie() {
        ExtentReportManager.log("Step 1: Creating a default movie");
        LogUtils.getLogger().info("Step 1: Creating a default movie");

		Movie createMovieResponse = MovieData.createDefaultMovie();
		int movieId = createMovieResponse.getId();

		Response response = MovieActions.deleteMovie(movieId);
		
		ExtentReportManager.log("Step 2: Performing assertion on the API response");
        LogUtils.getLogger().info("Step 2: Performing assertion on the API response");

		response.then()
			.spec(SpecBuilder.getResponseSpecification())
			.statusCode(StatusCode.CODE_200.getCode())
			.body("message", equalTo("Movie with id " + movieId + " deleted successfully"));
	}

	@AfterMethod
	public void tearDown(ITestResult result) {
        List<Integer> ids = (List<Integer>) result.getAttribute("cleanupIds");
        if (ids != null) {
            for (int id : ids) {
                try {
                    MovieActions.deleteMovie(id).then();
            		ExtentReportManager.log("In CleanUp > " + "Cleaned up Movie ID: " + id);
                    LogUtils.getLogger().info("In CleanUp > " + "Cleaned up Movie ID: " + id);

                    System.out.println("Cleaned up Movie ID: " + id);
                } catch (Exception e) {
            		ExtentReportManager.log("In CleanUp > " + "Failed to cleanup Movie ID: " + id);
                    LogUtils.getLogger().info("In CleanUp > " + "Failed to cleanup Movie ID: " + id);

                    System.err.println("Failed to cleanup Movie ID: " + id);
                }
            }
        }
	}
}
