package com.moviedb.tests.movies;

import static org.hamcrest.CoreMatchers.equalTo;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.samePropertyValuesAs;
import static org.testng.Assert.assertEquals;
import static org.testng.Assert.assertNotNull;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.testng.annotations.AfterMethod;
import org.testng.annotations.Test;
import org.testng.asserts.SoftAssert;

import com.moviedb.actions.MovieActions;
import com.moviedb.api.SpecBuilder;
import com.moviedb.pojos.movies.Cast;
import com.moviedb.pojos.movies.Crew;
import com.moviedb.pojos.movies.Finance;
import com.moviedb.pojos.movies.Movie;
import com.moviedb.pojos.movies.ReleaseDetails;

import api.utils.FakerUtils;
import io.restassured.response.Response;

public class MovieCrudTests {
	
	int movieId;

	//@BeforeClass
	private Movie movieBuilder() {
		String movieTitle = FakerUtils.generateMovieTitle();
		Crew crew = new Crew(FakerUtils.generateName(), FakerUtils.generateName(), FakerUtils.generateCompanyName());
		Cast cast1 = new Cast(FakerUtils.generateName(), FakerUtils.generateName(), List.of(
				FakerUtils.generateAward(), FakerUtils.generateAward()
		    ));
		Cast cast2 = new Cast(FakerUtils.generateName(), FakerUtils.generateName(), List.of(FakerUtils.generateAward()));
		Cast cast3 = new Cast(FakerUtils.generateName(), FakerUtils.generateName(), List.of(FakerUtils.generateAward()));
		List<String> genres = List.of(FakerUtils.generateGenre(), FakerUtils.generateGenre(), FakerUtils.generateGenre());
		ReleaseDetails releaseDetails= new ReleaseDetails(FakerUtils.generateCountry(), FakerUtils.generateCountry());
		Finance finance = new Finance(FakerUtils.generateAmount(), FakerUtils.generateAmount(), FakerUtils.generateAmount(), 
				FakerUtils.generateCurrency());

		return Movie.builder()
			.title(movieTitle)
			.crew(crew)
			.cast(List.of(cast1, cast2, cast3))
			.genres(genres)
			.releaseDetails(releaseDetails)
			.finance(finance)
			.build();
	}

	@Test(description = "Ensure that new movie is created when movie details provided is valid")
	public void shouldBeAbleToCreateAMovie() {
		Movie moviePayload = MovieData.getMoviePayload();
		Response response = MovieActions.createMovie(moviePayload);

		Movie movieResponse = response.then()
			.spec(SpecBuilder.getResponseSpecification())
			.statusCode(201)
			.extract()
			.as(Movie.class);

		movieId = movieResponse.getId();
		System.out.println("Id of the newly created movie is: " + movieId);

	    assertNotNull(movieResponse.getId(), "ID should be generated by API");
	    assertEquals(movieResponse.getTitle(), moviePayload.getTitle());
	    assertThat(movieResponse, samePropertyValuesAs(moviePayload, "id"));

	    SoftAssert softAssert = new SoftAssert();
	    softAssert.assertTrue(movieResponse.getId() > 0, "ID should be generated");
	    softAssert.assertEquals(movieResponse.getTitle(), moviePayload.getTitle());
	    softAssert.assertEquals(movieResponse.getFinance().getBoxOffice(), moviePayload.getFinance().getBoxOffice());
	    softAssert.assertAll();
	}
	
	@Test(description = "Ensure that multiple movies are created in a single create movie request")
	public void shouldBeAbleToCreateMultipleMoviesInASingleRequest() {
		List<Movie> movies = new ArrayList<>();
		movies.add(MovieData.getMoviePayload());
		movies.add(MovieData.getMoviePayload());
		movies.add(MovieData.getMoviePayload());

		Response response = MovieActions.createMultipleMovies(movies);

		response.then()
			.spec(SpecBuilder.getResponseSpecification())
			.statusCode(201)
			.body("inserted", equalTo(movies.size()));

		// Extract all titles into a List using JsonPath's GPath notation
		List<String> allTitles = response.jsonPath().getList("data.title");
		assertEquals(allTitles.get(0), movies.get(0).getTitle());
		assertEquals(allTitles.get(1), movies.get(1).getTitle());
		assertEquals(allTitles.get(2), movies.get(2).getTitle());

		// Extracts 'data' array and maps each element to a Movie object
		List<Movie> movieList = response.jsonPath().getList("data", Movie.class);
	    assertThat(movieList.get(0), samePropertyValuesAs(movies.get(0), "id"));
	    assertThat(movieList.get(1), samePropertyValuesAs(movies.get(1), "id"));
	    assertThat(movieList.get(2), samePropertyValuesAs(movies.get(2), "id"));    
	}

	@Test(description = "Ensure that movie information is updated when valid movie id is provided",
			dependsOnMethods = { "shouldBeAbleToCreateAMovie" })
	public void shouldBeAbleToUpdateAMovie() {
		Movie moviePayload = MovieData.getMoviePayload();
		Response response = MovieActions.createMovie(moviePayload);
		movieId = response.jsonPath().getInt("id");

		moviePayload.getFinance().setBudget(265000000L);
		response = MovieActions.updateMovie(movieId, moviePayload);

		Movie movieResponse = response.then()
			.spec(SpecBuilder.getResponseSpecification())
			.statusCode(200)
			.extract()
			.as(Movie.class);

		assertEquals(movieResponse.getId(), movieId);

	    assertNotNull(movieResponse.getId(), "ID should be generated by API");
		assertEquals(movieResponse.getTitle(), moviePayload.getTitle());
		assertEquals(movieResponse.getFinance().getBudget(), moviePayload.getFinance().getBudget());
	    assertThat(movieResponse, samePropertyValuesAs(moviePayload, "id"));
	}

	@Test(description = "Verify that a movie title can be partially updated using PATCH",
			dependsOnMethods = { "shouldBeAbleToUpdateAMovie" })
	public void shouldBeAbleToPatchUpdateAMovieTitleSuccessfully() {
		Movie moviePayload = MovieData.getMoviePayload();
		Response response = MovieActions.createMovie(moviePayload);
		movieId = response.jsonPath().getInt("id");

		String newMovieTitle = "Life Is Beautiful";
		Map<String, Object> updatePayload = new HashMap<>();
		updatePayload.put("title", newMovieTitle);

	    MovieActions.patchUpdateMovie(movieId, updatePayload)
	        .then()
	            .spec(SpecBuilder.getResponseSpecification())
	            .statusCode(200)
	            .body("title", equalTo(newMovieTitle))
	            .body("id", equalTo(movieId));
	}

	@Test(description = "Verify that movie poster can be uploaded to a movie",
			dependsOnMethods = { "shouldBeAbleToPatchUpdateAMovieTitleSuccessfully" })
	public void shouldBeAbleToUploadMoviePosterSuccessfully() {
		Movie moviePayload = MovieData.getMoviePayload();
		Response response = MovieActions.createMovie(moviePayload);
		movieId = response.jsonPath().getInt("id");
	    response = MovieActions.uploadMoviePoster("src/test/resources/data/Screenshot.png", movieId);

	    response.then()
            .spec(SpecBuilder.getResponseSpecification())
            .statusCode(201)
            .body("message", equalTo("Poster uploaded successfully"))
            .body("movieId", equalTo(movieId));

		System.out.println(response.jsonPath().getString("poster.filename"));
		System.out.println(response.jsonPath().getString("poster.mimetype"));
		System.out.println(response.jsonPath().getString("poster.size"));
	}

	@Test(description = "Ensure that a 200 OK is returned when a valid movie ID is deleted by an authorized user",
			dependsOnMethods = { "shouldBeAbleToUploadMoviePosterSuccessfully" })
	public void shouldBeAbleToDeleteAMovie() {
		Movie moviePayload = MovieData.getMoviePayload();
		Response response = MovieActions.createMovie(moviePayload);
		movieId = response.jsonPath().getInt("id");

		response = MovieActions.deleteMovie(movieId);
		response.then()
			.spec(SpecBuilder.getResponseSpecification())
			.statusCode(200)
			.body("message", equalTo("Movie with id " + movieId + " deleted successfully"));
	}

	@AfterMethod
	public void deleteMovie() {
		Response response = MovieActions.deleteMovie(movieId);
		response.then();
	}
	
}
