package com.moviedb.tests.movies;

import static org.hamcrest.CoreMatchers.equalTo;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.samePropertyValuesAs;
import static org.testng.Assert.assertEquals;
import static org.testng.Assert.assertNotNull;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;
import org.testng.asserts.SoftAssert;

import com.moviedb.actions.MovieActions;
import com.moviedb.api.SpecBuilder;
import com.moviedb.pojos.movies.Cast;
import com.moviedb.pojos.movies.Crew;
import com.moviedb.pojos.movies.Finance;
import com.moviedb.pojos.movies.Movie;
import com.moviedb.pojos.movies.ReleaseDetails;

import io.restassured.response.Response;

public class MovieCrudTests {
	
	int movieId;
	Movie moviePayload;
	
	@BeforeClass
	private Movie createMovie() {
		String movieTitle = "Life is too Beautiful";
		Crew crew = new Crew("Christopher Nolan", "Hans Zimmer", "Syncopy, Lynda Obst Productions, Legendary Pictures");
		Cast cast1 = new Cast("Matthew McConaughey", "Joseph Cooper", List.of(
		        "Saturn Award for Best Actor (Nominee)", 
		        "Critics' Choice Movie Award for Best Actor (Nominee)"
		    ));
		Cast cast2 = new Cast("Anne Hathaway", "Anne Hathaway", List.of(
		        "Saturn Award for Best Actress (Nominee)"));
		Cast cast3 = new Cast("Jessica Chastain", "Murphy Cooper (Adult)", List.of(
		        "Saturn Award for Best Supporting Actress (Nominee)"));
		List<String> genres = List.of("Sci-Fi", "Adventure", "Drama");
		ReleaseDetails releaseDetails= new ReleaseDetails("English", "United States, United Kingdom");
		Finance finance = new Finance(165000000L, 773800000L, 47200000L, "USD");

		moviePayload = Movie.builder()
			.title(movieTitle)
			.crew(crew)
			.cast(List.of(cast1, cast2, cast3))
			.genres(genres)
			.releaseDetails(releaseDetails)
			.finance(finance)
			.build();
		
		return moviePayload;
	}
	
	@Test(description = "Ensure that new movie is created when movie details provided is valid")
	public void givenValidMovieDetails_whenCreatingMovie_thenStatusIs201() {
		Response response = MovieActions.createMovie(moviePayload);

		Movie movieResponse = response.then()
			.spec(SpecBuilder.getResponseSpecification())
			.statusCode(201)
			.extract()
			.as(Movie.class);

		movieId = movieResponse.getId();
		System.out.println("Id of the newly created movie is: " + movieId);

	    assertNotNull(movieResponse.getId(), "ID should be generated by API");
	    assertEquals(movieResponse.getTitle(), moviePayload.getTitle());

	    SoftAssert softAssert = new SoftAssert();
	    softAssert.assertTrue(movieResponse.getId() > 0, "ID should be generated");
	    softAssert.assertEquals(movieResponse.getTitle(), moviePayload.getTitle());
	    softAssert.assertEquals(movieResponse.getFinance().getBoxOffice(), moviePayload.getFinance().getBoxOffice());
	    softAssert.assertAll();   
	}

	@Test(description = "Ensure that movie information is updated when valid movie id is provided",
			dependsOnMethods = { "givenValidMovieDetails_whenCreatingMovie_thenStatusIs201" })
	public void givenValidMovieId_whenUpdatingMovie_thenStatusIs200() {
		moviePayload.getFinance().setBudget(265000000L);
		Response response = MovieActions.updateMovie(movieId, moviePayload);

		Movie movieResponse = response.then()
			.spec(SpecBuilder.getResponseSpecification())
			.statusCode(200)
			.extract()
			.as(Movie.class);

		assertEquals(movieResponse.getId(), movieId);
		
	    assertNotNull(movieResponse.getId(), "ID should be generated by API");
		assertEquals(movieResponse.getTitle(), moviePayload.getTitle());
		assertEquals(movieResponse.getFinance().getBudget(), moviePayload.getFinance().getBudget());
	    assertThat(movieResponse, samePropertyValuesAs(moviePayload, "id"));

	}

	@Test(description = "Verify that a movie title can be partially updated using PATCH",
			dependsOnMethods = { "givenValidMovieId_whenUpdatingMovie_thenStatusIs200" })
	public void patchUpdateMovieTitleSuccessfully() {
		String newMovieTitle = "Life Is Beautiful";
		Map<String, Object> updatePayload = new HashMap<>();
		updatePayload.put("title", newMovieTitle);

	    MovieActions.patchUpdateMovie(movieId, updatePayload)
	        .then()
	            .spec(SpecBuilder.getResponseSpecification())
	            .statusCode(200)
	            .body("title", equalTo(newMovieTitle))
	            .body("id", equalTo(movieId));
	}

	@Test(description = "Ensure that a 200 OK is returned when a valid movie ID is deleted by an authorized user",
			dependsOnMethods = { "patchUpdateMovieTitleSuccessfully" })
	public void givenValidMovieId_whenDeletingMovie_thenStatusIs200() {
		Response response = MovieActions.deleteMovie(movieId);
		response.then()
			.spec(SpecBuilder.getResponseSpecification())
			.statusCode(200)
			.body("message", equalTo("Movie with id " + movieId + " deleted successfully"));
	}

	@AfterClass
	public void deleteMovie() {
		Response response = MovieActions.deleteMovie(movieId);
		response.then();
	}
	
}
